# Generated by Django 3.1.12 on 2024-12-29 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[7-9][0-9]{9}$', message='Phone number must start with 7-9 and have 10 digits.')])),
                ('state', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
