# Generated by Django 3.1.12 on 2025-01-02 07:53

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields
import my_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[7-9][0-9]{9}$', message='Phone number must start with 7-9 and have 10 digits.')])),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemename', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('age_range', models.CharField(default='0', max_length=50)),
                ('state', models.CharField(default='Maharashtra', max_length=50)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('income', models.CharField(default='0', max_length=50)),
                ('caste', djongo.models.fields.JSONField(default=list)),
                ('documents', djongo.models.fields.JSONField(default=list)),
                ('ministry', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'scheme',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[7-9][0-9]{9}$', message='Phone number must start with 7-9 and have 10 digits.')])),
                ('income', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('pincode', models.IntegerField(default=0)),
                ('city', models.CharField(default='', max_length=50)),
                ('district', models.CharField(default='', max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=25)),
                ('caste', models.CharField(default='general', max_length=30)),
                ('employment_status', models.CharField(default='unemployed', max_length=30)),
                ('marital_status', models.CharField(default='unmarried', max_length=30)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.CharField(default=my_app.models.generate_object_id, max_length=24, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=100)),
                ('schemename', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('applied_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('documents', djongo.models.fields.JSONField(blank=True, default=list)),
                ('uploaded_files', models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'])])),
            ],
        ),
    ]
