# Generated by Django 3.1.12 on 2024-12-29 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[7-9][0-9]{9}$', message='Phone number must start with 7-9 and have 10 digits.')])),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
