# Generated by Django 3.1.12 on 2025-01-01 09:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemename', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='caste',
            field=models.CharField(default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(default='unemployed', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(default='unmarried', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.IntegerField(default=0, max_length=6),
        ),
        migrations.CreateModel(
            name='SchemeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='scheme_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png'])])),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='my_app.scheme')),
            ],
        ),
    ]
