# Generated by Django 4.2 on 2024-12-30 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemename', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
             model_name='admin',
             name='id',
             field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
         ),
         migrations.AlterField(
             model_name='user',
             name='id',
             field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
         ),
        migrations.CreateModel(
            name='SchemeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='scheme_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png'])])),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='my_app.scheme')),
            ],
        ),
    ]
