# Generated by Django 3.1.12 on 2025-01-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20250101_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SchemeDocument',
        ),
    ]
