# Generated by Django 3.1.12 on 2025-01-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_scheme_alter_admin_id_alter_user_id_schemedocument'),
        ('my_app', '0004_auto_20250101_1456'),
    ]

    operations = [
    ]
