# Generated by Django 3.1.12 on 2025-01-01 11:36

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_merge_20250101_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='email',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='status',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='user_id',
        ),
        migrations.AddField(
            model_name='scheme',
            name='age_range',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='scheme',
            name='caste',
            field=djongo.models.fields.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scheme',
            name='employment_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='income',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='scheme',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='ministry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=50),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='SchemeDocument',
        ),
    ]
